// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gemis.proto

package me.takara.gemis.grpc;

public final class GemisGrpc {
  private GemisGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_takara_core_GrpcSyncStamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_takara_core_GrpcSyncStamp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_takara_core_GrpcPullReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_takara_core_GrpcPullReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_takara_core_GrpcPullResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_takara_core_GrpcPullResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_takara_core_GrpcBond_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_takara_core_GrpcBond_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_takara_core_GrpcEquity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_takara_core_GrpcEquity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_takara_core_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_takara_core_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_takara_core_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_takara_core_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Gemis.proto\022\016me.takara.core\".\n\rGrpcSyn" +
      "cStamp\022\n\n\002id\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001(\005\"Q\n" +
      "\013GrpcPullReq\0220\n\tsyncStamp\030\001 \001(\0132\035.me.tak" +
      "ara.core.GrpcSyncStamp\022\020\n\010pagesize\030\002 \001(\005" +
      "\"\227\001\n\014GrpcPullResp\0220\n\tsyncStamp\030\001 \001(\0132\035.m" +
      "e.takara.core.GrpcSyncStamp\022\'\n\005bonds\030\002 \003" +
      "(\0132\030.me.takara.core.GrpcBond\022,\n\010equities" +
      "\030\003 \003(\0132\032.me.takara.core.GrpcEquity\"4\n\010Gr" +
      "pcBond\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\016\n\006stat" +
      "us\030\003 \001(\t\"C\n\nGrpcEquity\022\n\n\002id\030\001 \001(\005\022\014\n\004na" +
      "me\030\002 \001(\t\022\016\n\006status\030\003 \001(\t\022\013\n\003ric\030\004 \001(\t\"\034\n" +
      "\014HelloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloRepl" +
      "y\022\017\n\007message\030\001 \001(\t2\241\001\n\024RemotePullingServ" +
      "ice\022A\n\004Pull\022\033.me.takara.core.GrpcPullReq" +
      "\032\034.me.takara.core.GrpcPullResp\022F\n\010SayHel" +
      "lo\022\034.me.takara.core.HelloRequest\032\032.me.ta" +
      "kara.core.HelloReply\"\000B&\n\024me.takara.gemi" +
      "s.grpcB\tGemisGrpcP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_me_takara_core_GrpcSyncStamp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_takara_core_GrpcSyncStamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_takara_core_GrpcSyncStamp_descriptor,
        new java.lang.String[] { "Id", "Timestamp", });
    internal_static_me_takara_core_GrpcPullReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_takara_core_GrpcPullReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_takara_core_GrpcPullReq_descriptor,
        new java.lang.String[] { "SyncStamp", "Pagesize", });
    internal_static_me_takara_core_GrpcPullResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_me_takara_core_GrpcPullResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_takara_core_GrpcPullResp_descriptor,
        new java.lang.String[] { "SyncStamp", "Bonds", "Equities", });
    internal_static_me_takara_core_GrpcBond_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_me_takara_core_GrpcBond_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_takara_core_GrpcBond_descriptor,
        new java.lang.String[] { "Id", "Name", "Status", });
    internal_static_me_takara_core_GrpcEquity_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_me_takara_core_GrpcEquity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_takara_core_GrpcEquity_descriptor,
        new java.lang.String[] { "Id", "Name", "Status", "Ric", });
    internal_static_me_takara_core_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_me_takara_core_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_takara_core_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_me_takara_core_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_me_takara_core_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_takara_core_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
