// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gemis.proto

package me.takara.gemis.grpc;

/**
 * Protobuf type {@code me.takara.core.GrpcPullReq}
 */
public final class GrpcPullReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.takara.core.GrpcPullReq)
    GrpcPullReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcPullReq.newBuilder() to construct.
  private GrpcPullReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcPullReq() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcPullReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GrpcPullReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            me.takara.gemis.grpc.GrpcSyncStamp.Builder subBuilder = null;
            if (syncStamp_ != null) {
              subBuilder = syncStamp_.toBuilder();
            }
            syncStamp_ = input.readMessage(me.takara.gemis.grpc.GrpcSyncStamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(syncStamp_);
              syncStamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            pagesize_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.takara.gemis.grpc.GrpcPullReq.class, me.takara.gemis.grpc.GrpcPullReq.Builder.class);
  }

  public static final int SYNCSTAMP_FIELD_NUMBER = 1;
  private me.takara.gemis.grpc.GrpcSyncStamp syncStamp_;
  /**
   * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
   * @return Whether the syncStamp field is set.
   */
  @java.lang.Override
  public boolean hasSyncStamp() {
    return syncStamp_ != null;
  }
  /**
   * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
   * @return The syncStamp.
   */
  @java.lang.Override
  public me.takara.gemis.grpc.GrpcSyncStamp getSyncStamp() {
    return syncStamp_ == null ? me.takara.gemis.grpc.GrpcSyncStamp.getDefaultInstance() : syncStamp_;
  }
  /**
   * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
   */
  @java.lang.Override
  public me.takara.gemis.grpc.GrpcSyncStampOrBuilder getSyncStampOrBuilder() {
    return getSyncStamp();
  }

  public static final int PAGESIZE_FIELD_NUMBER = 2;
  private int pagesize_;
  /**
   * <code>int32 pagesize = 2;</code>
   * @return The pagesize.
   */
  @java.lang.Override
  public int getPagesize() {
    return pagesize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (syncStamp_ != null) {
      output.writeMessage(1, getSyncStamp());
    }
    if (pagesize_ != 0) {
      output.writeInt32(2, pagesize_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (syncStamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSyncStamp());
    }
    if (pagesize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, pagesize_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.takara.gemis.grpc.GrpcPullReq)) {
      return super.equals(obj);
    }
    me.takara.gemis.grpc.GrpcPullReq other = (me.takara.gemis.grpc.GrpcPullReq) obj;

    if (hasSyncStamp() != other.hasSyncStamp()) return false;
    if (hasSyncStamp()) {
      if (!getSyncStamp()
          .equals(other.getSyncStamp())) return false;
    }
    if (getPagesize()
        != other.getPagesize()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSyncStamp()) {
      hash = (37 * hash) + SYNCSTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getSyncStamp().hashCode();
    }
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPagesize();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.takara.gemis.grpc.GrpcPullReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.takara.gemis.grpc.GrpcPullReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.takara.core.GrpcPullReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.takara.core.GrpcPullReq)
      me.takara.gemis.grpc.GrpcPullReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.takara.gemis.grpc.GrpcPullReq.class, me.takara.gemis.grpc.GrpcPullReq.Builder.class);
    }

    // Construct using me.takara.gemis.grpc.GrpcPullReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (syncStampBuilder_ == null) {
        syncStamp_ = null;
      } else {
        syncStamp_ = null;
        syncStampBuilder_ = null;
      }
      pagesize_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullReq_descriptor;
    }

    @java.lang.Override
    public me.takara.gemis.grpc.GrpcPullReq getDefaultInstanceForType() {
      return me.takara.gemis.grpc.GrpcPullReq.getDefaultInstance();
    }

    @java.lang.Override
    public me.takara.gemis.grpc.GrpcPullReq build() {
      me.takara.gemis.grpc.GrpcPullReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.takara.gemis.grpc.GrpcPullReq buildPartial() {
      me.takara.gemis.grpc.GrpcPullReq result = new me.takara.gemis.grpc.GrpcPullReq(this);
      if (syncStampBuilder_ == null) {
        result.syncStamp_ = syncStamp_;
      } else {
        result.syncStamp_ = syncStampBuilder_.build();
      }
      result.pagesize_ = pagesize_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.takara.gemis.grpc.GrpcPullReq) {
        return mergeFrom((me.takara.gemis.grpc.GrpcPullReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.takara.gemis.grpc.GrpcPullReq other) {
      if (other == me.takara.gemis.grpc.GrpcPullReq.getDefaultInstance()) return this;
      if (other.hasSyncStamp()) {
        mergeSyncStamp(other.getSyncStamp());
      }
      if (other.getPagesize() != 0) {
        setPagesize(other.getPagesize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      me.takara.gemis.grpc.GrpcPullReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (me.takara.gemis.grpc.GrpcPullReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private me.takara.gemis.grpc.GrpcSyncStamp syncStamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.takara.gemis.grpc.GrpcSyncStamp, me.takara.gemis.grpc.GrpcSyncStamp.Builder, me.takara.gemis.grpc.GrpcSyncStampOrBuilder> syncStampBuilder_;
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     * @return Whether the syncStamp field is set.
     */
    public boolean hasSyncStamp() {
      return syncStampBuilder_ != null || syncStamp_ != null;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     * @return The syncStamp.
     */
    public me.takara.gemis.grpc.GrpcSyncStamp getSyncStamp() {
      if (syncStampBuilder_ == null) {
        return syncStamp_ == null ? me.takara.gemis.grpc.GrpcSyncStamp.getDefaultInstance() : syncStamp_;
      } else {
        return syncStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public Builder setSyncStamp(me.takara.gemis.grpc.GrpcSyncStamp value) {
      if (syncStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        syncStamp_ = value;
        onChanged();
      } else {
        syncStampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public Builder setSyncStamp(
        me.takara.gemis.grpc.GrpcSyncStamp.Builder builderForValue) {
      if (syncStampBuilder_ == null) {
        syncStamp_ = builderForValue.build();
        onChanged();
      } else {
        syncStampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public Builder mergeSyncStamp(me.takara.gemis.grpc.GrpcSyncStamp value) {
      if (syncStampBuilder_ == null) {
        if (syncStamp_ != null) {
          syncStamp_ =
            me.takara.gemis.grpc.GrpcSyncStamp.newBuilder(syncStamp_).mergeFrom(value).buildPartial();
        } else {
          syncStamp_ = value;
        }
        onChanged();
      } else {
        syncStampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public Builder clearSyncStamp() {
      if (syncStampBuilder_ == null) {
        syncStamp_ = null;
        onChanged();
      } else {
        syncStamp_ = null;
        syncStampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public me.takara.gemis.grpc.GrpcSyncStamp.Builder getSyncStampBuilder() {
      
      onChanged();
      return getSyncStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public me.takara.gemis.grpc.GrpcSyncStampOrBuilder getSyncStampOrBuilder() {
      if (syncStampBuilder_ != null) {
        return syncStampBuilder_.getMessageOrBuilder();
      } else {
        return syncStamp_ == null ?
            me.takara.gemis.grpc.GrpcSyncStamp.getDefaultInstance() : syncStamp_;
      }
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.takara.gemis.grpc.GrpcSyncStamp, me.takara.gemis.grpc.GrpcSyncStamp.Builder, me.takara.gemis.grpc.GrpcSyncStampOrBuilder> 
        getSyncStampFieldBuilder() {
      if (syncStampBuilder_ == null) {
        syncStampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.takara.gemis.grpc.GrpcSyncStamp, me.takara.gemis.grpc.GrpcSyncStamp.Builder, me.takara.gemis.grpc.GrpcSyncStampOrBuilder>(
                getSyncStamp(),
                getParentForChildren(),
                isClean());
        syncStamp_ = null;
      }
      return syncStampBuilder_;
    }

    private int pagesize_ ;
    /**
     * <code>int32 pagesize = 2;</code>
     * @return The pagesize.
     */
    @java.lang.Override
    public int getPagesize() {
      return pagesize_;
    }
    /**
     * <code>int32 pagesize = 2;</code>
     * @param value The pagesize to set.
     * @return This builder for chaining.
     */
    public Builder setPagesize(int value) {
      
      pagesize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pagesize = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPagesize() {
      
      pagesize_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.takara.core.GrpcPullReq)
  }

  // @@protoc_insertion_point(class_scope:me.takara.core.GrpcPullReq)
  private static final me.takara.gemis.grpc.GrpcPullReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.takara.gemis.grpc.GrpcPullReq();
  }

  public static me.takara.gemis.grpc.GrpcPullReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcPullReq>
      PARSER = new com.google.protobuf.AbstractParser<GrpcPullReq>() {
    @java.lang.Override
    public GrpcPullReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GrpcPullReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcPullReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcPullReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.takara.gemis.grpc.GrpcPullReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

