// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gemis.proto

package me.takara.gemis.grpc;

public interface GrpcSyncStampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.takara.core.GrpcSyncStamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 timestamp = 2;</code>
   * @return The timestamp.
   */
  int getTimestamp();
}
