// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gemis.proto

package me.takara.gemis.grpc;

/**
 * Protobuf type {@code me.takara.core.GrpcPullResp}
 */
public final class GrpcPullResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.takara.core.GrpcPullResp)
    GrpcPullRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcPullResp.newBuilder() to construct.
  private GrpcPullResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcPullResp() {
    bonds_ = java.util.Collections.emptyList();
    equities_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcPullResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GrpcPullResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            me.takara.gemis.grpc.GrpcSyncStamp.Builder subBuilder = null;
            if (syncStamp_ != null) {
              subBuilder = syncStamp_.toBuilder();
            }
            syncStamp_ = input.readMessage(me.takara.gemis.grpc.GrpcSyncStamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(syncStamp_);
              syncStamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              bonds_ = new java.util.ArrayList<me.takara.gemis.grpc.GrpcBond>();
              mutable_bitField0_ |= 0x00000001;
            }
            bonds_.add(
                input.readMessage(me.takara.gemis.grpc.GrpcBond.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              equities_ = new java.util.ArrayList<me.takara.gemis.grpc.GrpcEquity>();
              mutable_bitField0_ |= 0x00000002;
            }
            equities_.add(
                input.readMessage(me.takara.gemis.grpc.GrpcEquity.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        bonds_ = java.util.Collections.unmodifiableList(bonds_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        equities_ = java.util.Collections.unmodifiableList(equities_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.takara.gemis.grpc.GrpcPullResp.class, me.takara.gemis.grpc.GrpcPullResp.Builder.class);
  }

  public static final int SYNCSTAMP_FIELD_NUMBER = 1;
  private me.takara.gemis.grpc.GrpcSyncStamp syncStamp_;
  /**
   * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
   * @return Whether the syncStamp field is set.
   */
  @java.lang.Override
  public boolean hasSyncStamp() {
    return syncStamp_ != null;
  }
  /**
   * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
   * @return The syncStamp.
   */
  @java.lang.Override
  public me.takara.gemis.grpc.GrpcSyncStamp getSyncStamp() {
    return syncStamp_ == null ? me.takara.gemis.grpc.GrpcSyncStamp.getDefaultInstance() : syncStamp_;
  }
  /**
   * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
   */
  @java.lang.Override
  public me.takara.gemis.grpc.GrpcSyncStampOrBuilder getSyncStampOrBuilder() {
    return getSyncStamp();
  }

  public static final int BONDS_FIELD_NUMBER = 2;
  private java.util.List<me.takara.gemis.grpc.GrpcBond> bonds_;
  /**
   * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
   */
  @java.lang.Override
  public java.util.List<me.takara.gemis.grpc.GrpcBond> getBondsList() {
    return bonds_;
  }
  /**
   * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends me.takara.gemis.grpc.GrpcBondOrBuilder> 
      getBondsOrBuilderList() {
    return bonds_;
  }
  /**
   * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
   */
  @java.lang.Override
  public int getBondsCount() {
    return bonds_.size();
  }
  /**
   * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
   */
  @java.lang.Override
  public me.takara.gemis.grpc.GrpcBond getBonds(int index) {
    return bonds_.get(index);
  }
  /**
   * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
   */
  @java.lang.Override
  public me.takara.gemis.grpc.GrpcBondOrBuilder getBondsOrBuilder(
      int index) {
    return bonds_.get(index);
  }

  public static final int EQUITIES_FIELD_NUMBER = 3;
  private java.util.List<me.takara.gemis.grpc.GrpcEquity> equities_;
  /**
   * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
   */
  @java.lang.Override
  public java.util.List<me.takara.gemis.grpc.GrpcEquity> getEquitiesList() {
    return equities_;
  }
  /**
   * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends me.takara.gemis.grpc.GrpcEquityOrBuilder> 
      getEquitiesOrBuilderList() {
    return equities_;
  }
  /**
   * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
   */
  @java.lang.Override
  public int getEquitiesCount() {
    return equities_.size();
  }
  /**
   * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
   */
  @java.lang.Override
  public me.takara.gemis.grpc.GrpcEquity getEquities(int index) {
    return equities_.get(index);
  }
  /**
   * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
   */
  @java.lang.Override
  public me.takara.gemis.grpc.GrpcEquityOrBuilder getEquitiesOrBuilder(
      int index) {
    return equities_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (syncStamp_ != null) {
      output.writeMessage(1, getSyncStamp());
    }
    for (int i = 0; i < bonds_.size(); i++) {
      output.writeMessage(2, bonds_.get(i));
    }
    for (int i = 0; i < equities_.size(); i++) {
      output.writeMessage(3, equities_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (syncStamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSyncStamp());
    }
    for (int i = 0; i < bonds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, bonds_.get(i));
    }
    for (int i = 0; i < equities_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, equities_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.takara.gemis.grpc.GrpcPullResp)) {
      return super.equals(obj);
    }
    me.takara.gemis.grpc.GrpcPullResp other = (me.takara.gemis.grpc.GrpcPullResp) obj;

    if (hasSyncStamp() != other.hasSyncStamp()) return false;
    if (hasSyncStamp()) {
      if (!getSyncStamp()
          .equals(other.getSyncStamp())) return false;
    }
    if (!getBondsList()
        .equals(other.getBondsList())) return false;
    if (!getEquitiesList()
        .equals(other.getEquitiesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSyncStamp()) {
      hash = (37 * hash) + SYNCSTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getSyncStamp().hashCode();
    }
    if (getBondsCount() > 0) {
      hash = (37 * hash) + BONDS_FIELD_NUMBER;
      hash = (53 * hash) + getBondsList().hashCode();
    }
    if (getEquitiesCount() > 0) {
      hash = (37 * hash) + EQUITIES_FIELD_NUMBER;
      hash = (53 * hash) + getEquitiesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.takara.gemis.grpc.GrpcPullResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.takara.gemis.grpc.GrpcPullResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.takara.core.GrpcPullResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.takara.core.GrpcPullResp)
      me.takara.gemis.grpc.GrpcPullRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.takara.gemis.grpc.GrpcPullResp.class, me.takara.gemis.grpc.GrpcPullResp.Builder.class);
    }

    // Construct using me.takara.gemis.grpc.GrpcPullResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBondsFieldBuilder();
        getEquitiesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (syncStampBuilder_ == null) {
        syncStamp_ = null;
      } else {
        syncStamp_ = null;
        syncStampBuilder_ = null;
      }
      if (bondsBuilder_ == null) {
        bonds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        bondsBuilder_.clear();
      }
      if (equitiesBuilder_ == null) {
        equities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        equitiesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.takara.gemis.grpc.GemisGrpc.internal_static_me_takara_core_GrpcPullResp_descriptor;
    }

    @java.lang.Override
    public me.takara.gemis.grpc.GrpcPullResp getDefaultInstanceForType() {
      return me.takara.gemis.grpc.GrpcPullResp.getDefaultInstance();
    }

    @java.lang.Override
    public me.takara.gemis.grpc.GrpcPullResp build() {
      me.takara.gemis.grpc.GrpcPullResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.takara.gemis.grpc.GrpcPullResp buildPartial() {
      me.takara.gemis.grpc.GrpcPullResp result = new me.takara.gemis.grpc.GrpcPullResp(this);
      int from_bitField0_ = bitField0_;
      if (syncStampBuilder_ == null) {
        result.syncStamp_ = syncStamp_;
      } else {
        result.syncStamp_ = syncStampBuilder_.build();
      }
      if (bondsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          bonds_ = java.util.Collections.unmodifiableList(bonds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bonds_ = bonds_;
      } else {
        result.bonds_ = bondsBuilder_.build();
      }
      if (equitiesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          equities_ = java.util.Collections.unmodifiableList(equities_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.equities_ = equities_;
      } else {
        result.equities_ = equitiesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.takara.gemis.grpc.GrpcPullResp) {
        return mergeFrom((me.takara.gemis.grpc.GrpcPullResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.takara.gemis.grpc.GrpcPullResp other) {
      if (other == me.takara.gemis.grpc.GrpcPullResp.getDefaultInstance()) return this;
      if (other.hasSyncStamp()) {
        mergeSyncStamp(other.getSyncStamp());
      }
      if (bondsBuilder_ == null) {
        if (!other.bonds_.isEmpty()) {
          if (bonds_.isEmpty()) {
            bonds_ = other.bonds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBondsIsMutable();
            bonds_.addAll(other.bonds_);
          }
          onChanged();
        }
      } else {
        if (!other.bonds_.isEmpty()) {
          if (bondsBuilder_.isEmpty()) {
            bondsBuilder_.dispose();
            bondsBuilder_ = null;
            bonds_ = other.bonds_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bondsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBondsFieldBuilder() : null;
          } else {
            bondsBuilder_.addAllMessages(other.bonds_);
          }
        }
      }
      if (equitiesBuilder_ == null) {
        if (!other.equities_.isEmpty()) {
          if (equities_.isEmpty()) {
            equities_ = other.equities_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEquitiesIsMutable();
            equities_.addAll(other.equities_);
          }
          onChanged();
        }
      } else {
        if (!other.equities_.isEmpty()) {
          if (equitiesBuilder_.isEmpty()) {
            equitiesBuilder_.dispose();
            equitiesBuilder_ = null;
            equities_ = other.equities_;
            bitField0_ = (bitField0_ & ~0x00000002);
            equitiesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEquitiesFieldBuilder() : null;
          } else {
            equitiesBuilder_.addAllMessages(other.equities_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      me.takara.gemis.grpc.GrpcPullResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (me.takara.gemis.grpc.GrpcPullResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private me.takara.gemis.grpc.GrpcSyncStamp syncStamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.takara.gemis.grpc.GrpcSyncStamp, me.takara.gemis.grpc.GrpcSyncStamp.Builder, me.takara.gemis.grpc.GrpcSyncStampOrBuilder> syncStampBuilder_;
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     * @return Whether the syncStamp field is set.
     */
    public boolean hasSyncStamp() {
      return syncStampBuilder_ != null || syncStamp_ != null;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     * @return The syncStamp.
     */
    public me.takara.gemis.grpc.GrpcSyncStamp getSyncStamp() {
      if (syncStampBuilder_ == null) {
        return syncStamp_ == null ? me.takara.gemis.grpc.GrpcSyncStamp.getDefaultInstance() : syncStamp_;
      } else {
        return syncStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public Builder setSyncStamp(me.takara.gemis.grpc.GrpcSyncStamp value) {
      if (syncStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        syncStamp_ = value;
        onChanged();
      } else {
        syncStampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public Builder setSyncStamp(
        me.takara.gemis.grpc.GrpcSyncStamp.Builder builderForValue) {
      if (syncStampBuilder_ == null) {
        syncStamp_ = builderForValue.build();
        onChanged();
      } else {
        syncStampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public Builder mergeSyncStamp(me.takara.gemis.grpc.GrpcSyncStamp value) {
      if (syncStampBuilder_ == null) {
        if (syncStamp_ != null) {
          syncStamp_ =
            me.takara.gemis.grpc.GrpcSyncStamp.newBuilder(syncStamp_).mergeFrom(value).buildPartial();
        } else {
          syncStamp_ = value;
        }
        onChanged();
      } else {
        syncStampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public Builder clearSyncStamp() {
      if (syncStampBuilder_ == null) {
        syncStamp_ = null;
        onChanged();
      } else {
        syncStamp_ = null;
        syncStampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public me.takara.gemis.grpc.GrpcSyncStamp.Builder getSyncStampBuilder() {
      
      onChanged();
      return getSyncStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    public me.takara.gemis.grpc.GrpcSyncStampOrBuilder getSyncStampOrBuilder() {
      if (syncStampBuilder_ != null) {
        return syncStampBuilder_.getMessageOrBuilder();
      } else {
        return syncStamp_ == null ?
            me.takara.gemis.grpc.GrpcSyncStamp.getDefaultInstance() : syncStamp_;
      }
    }
    /**
     * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.takara.gemis.grpc.GrpcSyncStamp, me.takara.gemis.grpc.GrpcSyncStamp.Builder, me.takara.gemis.grpc.GrpcSyncStampOrBuilder> 
        getSyncStampFieldBuilder() {
      if (syncStampBuilder_ == null) {
        syncStampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.takara.gemis.grpc.GrpcSyncStamp, me.takara.gemis.grpc.GrpcSyncStamp.Builder, me.takara.gemis.grpc.GrpcSyncStampOrBuilder>(
                getSyncStamp(),
                getParentForChildren(),
                isClean());
        syncStamp_ = null;
      }
      return syncStampBuilder_;
    }

    private java.util.List<me.takara.gemis.grpc.GrpcBond> bonds_ =
      java.util.Collections.emptyList();
    private void ensureBondsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        bonds_ = new java.util.ArrayList<me.takara.gemis.grpc.GrpcBond>(bonds_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.takara.gemis.grpc.GrpcBond, me.takara.gemis.grpc.GrpcBond.Builder, me.takara.gemis.grpc.GrpcBondOrBuilder> bondsBuilder_;

    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public java.util.List<me.takara.gemis.grpc.GrpcBond> getBondsList() {
      if (bondsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bonds_);
      } else {
        return bondsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public int getBondsCount() {
      if (bondsBuilder_ == null) {
        return bonds_.size();
      } else {
        return bondsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public me.takara.gemis.grpc.GrpcBond getBonds(int index) {
      if (bondsBuilder_ == null) {
        return bonds_.get(index);
      } else {
        return bondsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public Builder setBonds(
        int index, me.takara.gemis.grpc.GrpcBond value) {
      if (bondsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBondsIsMutable();
        bonds_.set(index, value);
        onChanged();
      } else {
        bondsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public Builder setBonds(
        int index, me.takara.gemis.grpc.GrpcBond.Builder builderForValue) {
      if (bondsBuilder_ == null) {
        ensureBondsIsMutable();
        bonds_.set(index, builderForValue.build());
        onChanged();
      } else {
        bondsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public Builder addBonds(me.takara.gemis.grpc.GrpcBond value) {
      if (bondsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBondsIsMutable();
        bonds_.add(value);
        onChanged();
      } else {
        bondsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public Builder addBonds(
        int index, me.takara.gemis.grpc.GrpcBond value) {
      if (bondsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBondsIsMutable();
        bonds_.add(index, value);
        onChanged();
      } else {
        bondsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public Builder addBonds(
        me.takara.gemis.grpc.GrpcBond.Builder builderForValue) {
      if (bondsBuilder_ == null) {
        ensureBondsIsMutable();
        bonds_.add(builderForValue.build());
        onChanged();
      } else {
        bondsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public Builder addBonds(
        int index, me.takara.gemis.grpc.GrpcBond.Builder builderForValue) {
      if (bondsBuilder_ == null) {
        ensureBondsIsMutable();
        bonds_.add(index, builderForValue.build());
        onChanged();
      } else {
        bondsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public Builder addAllBonds(
        java.lang.Iterable<? extends me.takara.gemis.grpc.GrpcBond> values) {
      if (bondsBuilder_ == null) {
        ensureBondsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bonds_);
        onChanged();
      } else {
        bondsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public Builder clearBonds() {
      if (bondsBuilder_ == null) {
        bonds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bondsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public Builder removeBonds(int index) {
      if (bondsBuilder_ == null) {
        ensureBondsIsMutable();
        bonds_.remove(index);
        onChanged();
      } else {
        bondsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public me.takara.gemis.grpc.GrpcBond.Builder getBondsBuilder(
        int index) {
      return getBondsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public me.takara.gemis.grpc.GrpcBondOrBuilder getBondsOrBuilder(
        int index) {
      if (bondsBuilder_ == null) {
        return bonds_.get(index);  } else {
        return bondsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public java.util.List<? extends me.takara.gemis.grpc.GrpcBondOrBuilder> 
         getBondsOrBuilderList() {
      if (bondsBuilder_ != null) {
        return bondsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bonds_);
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public me.takara.gemis.grpc.GrpcBond.Builder addBondsBuilder() {
      return getBondsFieldBuilder().addBuilder(
          me.takara.gemis.grpc.GrpcBond.getDefaultInstance());
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public me.takara.gemis.grpc.GrpcBond.Builder addBondsBuilder(
        int index) {
      return getBondsFieldBuilder().addBuilder(
          index, me.takara.gemis.grpc.GrpcBond.getDefaultInstance());
    }
    /**
     * <code>repeated .me.takara.core.GrpcBond bonds = 2;</code>
     */
    public java.util.List<me.takara.gemis.grpc.GrpcBond.Builder> 
         getBondsBuilderList() {
      return getBondsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.takara.gemis.grpc.GrpcBond, me.takara.gemis.grpc.GrpcBond.Builder, me.takara.gemis.grpc.GrpcBondOrBuilder> 
        getBondsFieldBuilder() {
      if (bondsBuilder_ == null) {
        bondsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            me.takara.gemis.grpc.GrpcBond, me.takara.gemis.grpc.GrpcBond.Builder, me.takara.gemis.grpc.GrpcBondOrBuilder>(
                bonds_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        bonds_ = null;
      }
      return bondsBuilder_;
    }

    private java.util.List<me.takara.gemis.grpc.GrpcEquity> equities_ =
      java.util.Collections.emptyList();
    private void ensureEquitiesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        equities_ = new java.util.ArrayList<me.takara.gemis.grpc.GrpcEquity>(equities_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.takara.gemis.grpc.GrpcEquity, me.takara.gemis.grpc.GrpcEquity.Builder, me.takara.gemis.grpc.GrpcEquityOrBuilder> equitiesBuilder_;

    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public java.util.List<me.takara.gemis.grpc.GrpcEquity> getEquitiesList() {
      if (equitiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(equities_);
      } else {
        return equitiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public int getEquitiesCount() {
      if (equitiesBuilder_ == null) {
        return equities_.size();
      } else {
        return equitiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public me.takara.gemis.grpc.GrpcEquity getEquities(int index) {
      if (equitiesBuilder_ == null) {
        return equities_.get(index);
      } else {
        return equitiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public Builder setEquities(
        int index, me.takara.gemis.grpc.GrpcEquity value) {
      if (equitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEquitiesIsMutable();
        equities_.set(index, value);
        onChanged();
      } else {
        equitiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public Builder setEquities(
        int index, me.takara.gemis.grpc.GrpcEquity.Builder builderForValue) {
      if (equitiesBuilder_ == null) {
        ensureEquitiesIsMutable();
        equities_.set(index, builderForValue.build());
        onChanged();
      } else {
        equitiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public Builder addEquities(me.takara.gemis.grpc.GrpcEquity value) {
      if (equitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEquitiesIsMutable();
        equities_.add(value);
        onChanged();
      } else {
        equitiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public Builder addEquities(
        int index, me.takara.gemis.grpc.GrpcEquity value) {
      if (equitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEquitiesIsMutable();
        equities_.add(index, value);
        onChanged();
      } else {
        equitiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public Builder addEquities(
        me.takara.gemis.grpc.GrpcEquity.Builder builderForValue) {
      if (equitiesBuilder_ == null) {
        ensureEquitiesIsMutable();
        equities_.add(builderForValue.build());
        onChanged();
      } else {
        equitiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public Builder addEquities(
        int index, me.takara.gemis.grpc.GrpcEquity.Builder builderForValue) {
      if (equitiesBuilder_ == null) {
        ensureEquitiesIsMutable();
        equities_.add(index, builderForValue.build());
        onChanged();
      } else {
        equitiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public Builder addAllEquities(
        java.lang.Iterable<? extends me.takara.gemis.grpc.GrpcEquity> values) {
      if (equitiesBuilder_ == null) {
        ensureEquitiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, equities_);
        onChanged();
      } else {
        equitiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public Builder clearEquities() {
      if (equitiesBuilder_ == null) {
        equities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        equitiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public Builder removeEquities(int index) {
      if (equitiesBuilder_ == null) {
        ensureEquitiesIsMutable();
        equities_.remove(index);
        onChanged();
      } else {
        equitiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public me.takara.gemis.grpc.GrpcEquity.Builder getEquitiesBuilder(
        int index) {
      return getEquitiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public me.takara.gemis.grpc.GrpcEquityOrBuilder getEquitiesOrBuilder(
        int index) {
      if (equitiesBuilder_ == null) {
        return equities_.get(index);  } else {
        return equitiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public java.util.List<? extends me.takara.gemis.grpc.GrpcEquityOrBuilder> 
         getEquitiesOrBuilderList() {
      if (equitiesBuilder_ != null) {
        return equitiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(equities_);
      }
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public me.takara.gemis.grpc.GrpcEquity.Builder addEquitiesBuilder() {
      return getEquitiesFieldBuilder().addBuilder(
          me.takara.gemis.grpc.GrpcEquity.getDefaultInstance());
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public me.takara.gemis.grpc.GrpcEquity.Builder addEquitiesBuilder(
        int index) {
      return getEquitiesFieldBuilder().addBuilder(
          index, me.takara.gemis.grpc.GrpcEquity.getDefaultInstance());
    }
    /**
     * <code>repeated .me.takara.core.GrpcEquity equities = 3;</code>
     */
    public java.util.List<me.takara.gemis.grpc.GrpcEquity.Builder> 
         getEquitiesBuilderList() {
      return getEquitiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.takara.gemis.grpc.GrpcEquity, me.takara.gemis.grpc.GrpcEquity.Builder, me.takara.gemis.grpc.GrpcEquityOrBuilder> 
        getEquitiesFieldBuilder() {
      if (equitiesBuilder_ == null) {
        equitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            me.takara.gemis.grpc.GrpcEquity, me.takara.gemis.grpc.GrpcEquity.Builder, me.takara.gemis.grpc.GrpcEquityOrBuilder>(
                equities_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        equities_ = null;
      }
      return equitiesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.takara.core.GrpcPullResp)
  }

  // @@protoc_insertion_point(class_scope:me.takara.core.GrpcPullResp)
  private static final me.takara.gemis.grpc.GrpcPullResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.takara.gemis.grpc.GrpcPullResp();
  }

  public static me.takara.gemis.grpc.GrpcPullResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcPullResp>
      PARSER = new com.google.protobuf.AbstractParser<GrpcPullResp>() {
    @java.lang.Override
    public GrpcPullResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GrpcPullResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcPullResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcPullResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.takara.gemis.grpc.GrpcPullResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

