// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gemis.proto

package me.takara.gemis.grpc;

public interface GrpcPullReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.takara.core.GrpcPullReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
   * @return Whether the syncStamp field is set.
   */
  boolean hasSyncStamp();
  /**
   * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
   * @return The syncStamp.
   */
  me.takara.gemis.grpc.GrpcSyncStamp getSyncStamp();
  /**
   * <code>.me.takara.core.GrpcSyncStamp syncStamp = 1;</code>
   */
  me.takara.gemis.grpc.GrpcSyncStampOrBuilder getSyncStampOrBuilder();

  /**
   * <code>int32 pagesize = 2;</code>
   * @return The pagesize.
   */
  int getPagesize();
}
