// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gemis.proto

package me.takara.gemis.grpc;

/**
 * Protobuf service {@code me.takara.core.RemotePullingService}
 */
public  abstract class RemotePullingService
    implements com.google.protobuf.Service {
  protected RemotePullingService() {}

  public interface Interface {
    /**
     * <code>rpc Pull(.me.takara.core.GrpcPullReq) returns (.me.takara.core.GrpcPullResp);</code>
     */
    public abstract void pull(
        com.google.protobuf.RpcController controller,
        me.takara.gemis.grpc.GrpcPullReq request,
        com.google.protobuf.RpcCallback<me.takara.gemis.grpc.GrpcPullResp> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new RemotePullingService() {
      @java.lang.Override
      public  void pull(
          com.google.protobuf.RpcController controller,
          me.takara.gemis.grpc.GrpcPullReq request,
          com.google.protobuf.RpcCallback<me.takara.gemis.grpc.GrpcPullResp> done) {
        impl.pull(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.pull(controller, (me.takara.gemis.grpc.GrpcPullReq)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return me.takara.gemis.grpc.GrpcPullReq.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return me.takara.gemis.grpc.GrpcPullResp.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc Pull(.me.takara.core.GrpcPullReq) returns (.me.takara.core.GrpcPullResp);</code>
   */
  public abstract void pull(
      com.google.protobuf.RpcController controller,
      me.takara.gemis.grpc.GrpcPullReq request,
      com.google.protobuf.RpcCallback<me.takara.gemis.grpc.GrpcPullResp> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return me.takara.gemis.grpc.GemisGrpc.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.pull(controller, (me.takara.gemis.grpc.GrpcPullReq)request,
          com.google.protobuf.RpcUtil.<me.takara.gemis.grpc.GrpcPullResp>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return me.takara.gemis.grpc.GrpcPullReq.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return me.takara.gemis.grpc.GrpcPullResp.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends me.takara.gemis.grpc.RemotePullingService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void pull(
        com.google.protobuf.RpcController controller,
        me.takara.gemis.grpc.GrpcPullReq request,
        com.google.protobuf.RpcCallback<me.takara.gemis.grpc.GrpcPullResp> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        me.takara.gemis.grpc.GrpcPullResp.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          me.takara.gemis.grpc.GrpcPullResp.class,
          me.takara.gemis.grpc.GrpcPullResp.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public me.takara.gemis.grpc.GrpcPullResp pull(
        com.google.protobuf.RpcController controller,
        me.takara.gemis.grpc.GrpcPullReq request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public me.takara.gemis.grpc.GrpcPullResp pull(
        com.google.protobuf.RpcController controller,
        me.takara.gemis.grpc.GrpcPullReq request)
        throws com.google.protobuf.ServiceException {
      return (me.takara.gemis.grpc.GrpcPullResp) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        me.takara.gemis.grpc.GrpcPullResp.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:me.takara.core.RemotePullingService)
}

